// Generated by Wrangler by running `wrangler types`

interface Env {
	MY_VAR: "my-variable";
	ENVIRONMENT: "dev";
	CORS_ORIGINS: "http://localhost:3000";
	FPX_ENDPOINT: string;
	SECRET_KEY: string;
	JWT_SNACK: string;
	JWT_SUB: string;
	MY_BUCKET: R2Bucket;
	DB: D1Database;
}
