// Generated by Wrangler by running `wrangler types`

interface Env {
	MY_VAR: "my-variable";
	CORS_ORIGIN: "http://localhost:3000, https://open.spotify.com";
	FPX_ENDPOINT: string;
	SECRET_KEY: string;
	JWT_SNACK: string;
	JWT_SUB: string;
	MY_BUCKET: R2Bucket;
	DB: D1Database;
}
